### PR TITLE
Update the tracker to handle mobile devices

### PR DESCRIPTION
**Pull request by kmoorestevenson**
-Updating the unity engine and Mono.Data.SqliteClient dll's to Unity 2018.3.6f1
-Adding sqlite native files needed for Android devices
-Allowing the user to define the database's and session location within a device

### CODE REVIEW

**Comment by dbuscaglia** [comment]
@mhadam This is the update I was discussing referecing: https://github.com/snowplow/snowplow-unity-tracker/pull/8

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by kmoorestevenson** [comment]
> Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.
> 
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I have signed the agreement.

**Comment by dbuscaglia** [comment]
@mhadam @BenFradet  giving this a bump :)

**Comment by mhadam** [comment]
thanks! will handle this now

**Comment by snowplowcla** [comment]
Confirmed! @kmoorestevenson  has signed the Individual Contributor License Agreement. Thanks so much

**Pull request closed without merging**
